apiVersion: v2
name: frontend
description: A Helm chart for the DevOps Playground Frontend application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - frontend
  - nginx
  - static
  - devops
home: https://github.com/your-org/devops-playground
sources:
  - https://github.com/your-org/devops-playground
maintainers:
  - name: DevOps Team
    email: devops@example.com
