apiVersion: v2
name: api
description: A Helm chart for the DevOps Playground API application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - api
  - flask
  - python
  - devops
home: https://github.com/your-org/devops-playground
sources:
  - https://github.com/your-org/devops-playground
maintainers:
  - name: DevOps Team
    email: devops@example.com
