name: Terraform Plan

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'

env:
  TF_VERSION: '1.6.0'
  AWS_REGION: 'us-east-1'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive terraform/

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest

    - name: TFLint
      run: |
        cd terraform/envs/${{ matrix.environment }}
        tflint --init
        tflint --format sarif --out tflint-results.sarif

    - name: Upload TFLint results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: terraform/envs/${{ matrix.environment }}/tflint-results.sarif

    - name: Setup TFSec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: terraform/envs/${{ matrix.environment }}
        soft_fail: true

    - name: Terraform Init
      run: |
        cd terraform/envs/${{ matrix.environment }}
        terraform init -backend-config="../../backend-config.hcl"

    - name: Terraform Validate
      run: |
        cd terraform/envs/${{ matrix.environment }}
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform/envs/${{ matrix.environment }}
        terraform plan -var-file="../../terraform.tfvars" -out=tfplan
      env:
        TF_VAR_environment: ${{ matrix.environment }}

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan-${{ matrix.environment }}
        path: terraform/envs/${{ matrix.environment }}/tfplan
        retention-days: 5
