apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-playground-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Yancers/devops-playground
    targetRevision: HEAD
    path: charts/api
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: database.host
          value: "devops-playground-dev-db.cluster-xyz.us-east-1.rds.amazonaws.com"
        - name: database.passwordSecret
          value: "rds-credentials"
        - name: redis.host
          value: "redis-service"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
